server:
  port: 10087
spring:
  application:
    name: idc-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
zuul:
  prefix: / # 添加路由前缀
  routes:
    idc-asset:
          path: /**
          serviceId: idc-asset
    auth-service:
          path: /auth/**
          serviceId: auth-service
  sensitive-headers: #忽略请求头设置为null
idc:
  cors:
    allowedOrigins:
      - http:/localhost
    allowedCredentials: true
    allowedHeaders:
      - "*"
    allowedMethods:
      - GET
      - POST
      - DELETE
      - PUT
      - OPTIONS
      - HEAD
    maxAge: 86400
    filterPath: "/**"

